# Assignment 1: Numpy

Perform the follwing tasks:


In [30]:
#3.1: import the numpy library
import numpy as np 

In [31]:
#3.2: create a random 10x10 array named A
A = np.random.rand(10,10)
A

array([[0.72466823, 0.76874213, 0.46946658, 0.38452872, 0.65002607,
        0.1935412 , 0.28105342, 0.11202868, 0.28136105, 0.84716744],
       [0.94975254, 0.54122725, 0.86911822, 0.82098849, 0.71375751,
        0.04494956, 0.18470491, 0.63953579, 0.93379753, 0.84249064],
       [0.55399988, 0.53418739, 0.15572571, 0.18623306, 0.68529762,
        0.1072038 , 0.06473885, 0.03107778, 0.76674963, 0.45258857],
       [0.19610191, 0.07325791, 0.54530162, 0.50179421, 0.75607524,
        0.44578219, 0.4726322 , 0.92993215, 0.30906205, 0.24139539],
       [0.57260859, 0.88641432, 0.70890948, 0.29783216, 0.46003994,
        0.42919193, 0.20733579, 0.4657254 , 0.41032042, 0.27950923],
       [0.78190211, 0.36090511, 0.45510461, 0.13079012, 0.40212863,
        0.69128766, 0.75191612, 0.01858772, 0.39831292, 0.60809723],
       [0.78171821, 0.68437466, 0.51508435, 0.47211988, 0.13495441,
        0.03037381, 0.77187895, 0.71631918, 0.27964294, 0.9408168 ],
       [0.79620241, 0.35661248, 0.5282907

In [35]:
#3.3: return only the odd rows of A
A[::2]

array([[0.72466823, 0.76874213, 0.46946658, 0.38452872, 0.65002607,
        0.1935412 , 0.28105342, 0.11202868, 0.28136105, 0.84716744],
       [0.55399988, 0.53418739, 0.15572571, 0.18623306, 0.68529762,
        0.1072038 , 0.06473885, 0.03107778, 0.76674963, 0.45258857],
       [0.57260859, 0.88641432, 0.70890948, 0.29783216, 0.46003994,
        0.42919193, 0.20733579, 0.4657254 , 0.41032042, 0.27950923],
       [0.78171821, 0.68437466, 0.51508435, 0.47211988, 0.13495441,
        0.03037381, 0.77187895, 0.71631918, 0.27964294, 0.9408168 ],
       [0.74196974, 0.686674  , 0.4790147 , 0.60927648, 0.16927089,
        0.02861598, 0.41681629, 0.24412152, 0.71781086, 0.26070757]])

In [33]:
#3.4: perform a matrix multiplication of A with it's transposed
A * np.transpose(A)

array([[0.52514404, 0.73011479, 0.26008443, 0.07540682, 0.37221051,
        0.15133028, 0.21970457, 0.0891975 , 0.20876138, 0.04779306],
       [0.73011479, 0.29292694, 0.46427199, 0.0601439 , 0.63268488,
        0.01622253, 0.12640736, 0.22806645, 0.64121449, 0.4180722 ],
       [0.26008443, 0.46427199, 0.0242505 , 0.10155319, 0.48581398,
        0.04878894, 0.03334597, 0.0164181 , 0.36728435, 0.07718352],
       [0.07540682, 0.0601439 , 0.10155319, 0.25179743, 0.22518352,
        0.05830391, 0.22313906, 0.90855916, 0.18830424, 0.09564294],
       [0.37221051, 0.63268488, 0.48581398, 0.22518352, 0.21163675,
        0.17259036, 0.02798088, 0.35518869, 0.0694553 , 0.23797866],
       [0.15133028, 0.01622253, 0.04878894, 0.05830391, 0.17259036,
        0.47787863, 0.02283856, 0.00909127, 0.01139812, 0.46327052],
       [0.21970457, 0.12640736, 0.03334597, 0.22313906, 0.02798088,
        0.02283856, 0.59579712, 0.66917328, 0.11655973, 0.42671035],
       [0.0891975 , 0.22806645, 0.0164181

In [25]:
#3.5: compute the matrix inverse of A
np.linalg.inv(A)

array([[ 0.89256901, -1.04345871,  0.25521757, -0.23677389,  0.11346094,
         2.08761153,  1.60488203, -1.82695364, -0.73950683, -1.21881985],
       [ 2.13688223, -1.51110771, -0.81327218, -0.64384868,  1.27704884,
        -0.50393955, -2.84745328,  2.42543886,  0.99742932, -0.74442231],
       [-1.46914452, -0.39552028,  1.34481586,  0.66533144, -1.36482946,
         1.59870365,  3.99111572, -2.65632575, -1.4833653 ,  0.34636952],
       [-1.84236706,  1.38303805, -0.39479373, -0.56993587, -0.04357372,
         0.50041134,  1.788018  , -1.06821162, -0.23046595,  0.87197867],
       [ 1.01831979,  0.4701573 ,  0.70579641,  1.85848097,  2.25754045,
        -1.98505741, -0.69345529, -1.1077695 , -0.79915096, -1.40733067],
       [ 0.16777883,  2.07601547,  1.17599161,  0.73012156, -0.64636172,
        -3.03763002, -0.73378132,  1.04328292, -0.25118043, -0.59528626],
       [-0.68581693,  0.01289186,  1.34244822,  1.8874447 ,  0.44850924,
        -0.39180905,  0.34316108, -0.26072988

In [29]:
#3.6: divide all entries of A which are lager than 0.5 by 2 (hint: use where() )
np.where(A > 0.5, A/2, A)

array([[0.40306932, 0.26012013, 0.37734641, 0.42891628, 0.28396897,
        0.38167694, 0.47006611, 0.29417988, 0.41188718, 0.43392305],
       [0.47521774, 0.11710046, 0.20565482, 0.37267583, 0.35027513,
        0.3707832 , 0.39537737, 0.28183114, 0.39949013, 0.36844388],
       [0.42832754, 0.32335527, 0.32609795, 0.35241539, 0.37331506,
        0.30626165, 0.35494198, 0.45168139, 0.49159186, 0.11785143],
       [0.21926312, 0.06776877, 0.25004466, 0.12947467, 0.31426924,
        0.27360724, 0.44878353, 0.34758809, 0.26938619, 0.44751661],
       [0.41727086, 0.35340415, 0.26982197, 0.47484833, 0.48970997,
        0.28399161, 0.41070457, 0.3299784 , 0.28955979, 0.30060873],
       [0.46726276, 0.10833655, 0.24717212, 0.26003572, 0.21926818,
        0.41318243, 0.47612563, 0.2860553 , 0.3981886 , 0.31971649],
       [0.26886309, 0.47912636, 0.36275503, 0.45404257, 0.22028769,
        0.28485347, 0.3606174 , 0.17094382, 0.43534735, 0.32298561],
       [0.31196599, 0.46612916, 0.3244155